# Output settings
output:
  directory: output_data             # Directory for generated test data files
  save_timestamp: true               # Whether to include timestamp in filenames
  timestamp_format: "%Y%m%d_%H%M%S"  # Format for timestamps

# Serial communication configuration
serial:
  # Basic connection settings
  com_port: "COM5"                 # Default serial port identifier
  baud_rate: 115200                # Communication speed in bits per second

  # Mock device settings (used if use_mock_device is true)
  use_mock_device: true            # Use simulated device instead of real hardware
  mock_port_name: "MOCK_COM"         # Name for the simulated COM port

  # Handshake settings (for initial :00 -> :55... check)
  perform_handshake: true          # Whether to perform the handshake after connect
  handshake_timeout_s: 0.5           # Max time for handshake response
  handshake_poll_interval_s: 0.01    # Interval between handshake poll reads

  # Command execution controls
  command_timeout: 30.0            # Maximum time to wait for a complete response in seconds
  command_retry_count: 3           # Number of retry attempts if a command fails
  command_delay: 0.05              # Delay between consecutive commands to prevent device overload in seconds

  # Response detection settings
  read_timeout: 0.1                # Timeout for individual read operations in seconds
  response_idle_threshold: 3       # Number of consecutive empty reads to consider a response complete

  # Error handling
  on_no_response_action: "retry"   # What to do when no response: "retry", "continue", or "stop"

  # Connection management
  reconnect_delay: 1.0             # Delay before attempting to reconnect in seconds

  # Debugging
  log_interval: 1.0                # How often to log waiting status messages in seconds
  read_interval: 0.01              # Interval between read attempts in seconds (used by wait_for_response) 